# Package stage
FROM openjdk:11-jre-slim
COPY ./server/build/libs/salog-0.0.1-SNAPSHOT.jar /app/salog.jar
COPY /home/ec2-user/keystore.p12 /app/keystore.p12
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/salog.jar"]
